spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    com.yourorg.aiplatform: INFO
